name: check

on: push

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup V environment
      uses: nocturlab/setup-vlang-action@v1.1.2

    - name: fmt
      run: v fmt -c ./src/*.v
