name: check

on: push

jobs:
  build:
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup V environment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/vlang/v
        cd v
        make
        sudo ./v symlink
        cd ../

    - name: fmt
      run: |
        find ./src -name "*.v" | xargs v fmt -c
    
    - name: test
      run: |
        find ./src -name "*_test.v" | xargs v test
